@host = http://dev-api1.leigod.com/

POST {{host}}client/login
Content-Type: application/x-www-form-urlencoded

{
  "lang": "cn",
  "country_code": 86,
  "user_type": 0,
  "mobile_num": "15271871141",
  "password": "e10adc3949ba59abbe56e057f20f883e",
  "os_type": 3,
  "client_version": "1.0.0",
  "hardware_id": "hardware_id",
  "device_info": "device_info",
  "region_code": 1,
  "src_channel": "src_channel"
}

###

POST {{host}}api/auth/register/package
Content-Type: application/json

{
  "user_type": 0,
  "region_code": 1
}
