@host = http://dev-api1.leigod.com/

POST {{host}}api/auth/login
Content-Type: application/json

{
  "country_code": 86,
  "user_type": 0,
  "username": "15271871141",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

###

POST {{host}}api/auth/register/package
Content-Type: application/json

{
  "user_type": 0,
  "region_code": 1
}
